// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jonathanarnault/cgear-go/go/discord/command (interfaces: CommandBuilder)

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	discord "github.com/jonathanarnault/cgear-go/go/discord"
)

// MockCommandBuilder is a mock of CommandBuilder interface.
type MockCommandBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockCommandBuilderMockRecorder
}

// MockCommandBuilderMockRecorder is the mock recorder for MockCommandBuilder.
type MockCommandBuilderMockRecorder struct {
	mock *MockCommandBuilder
}

// NewMockCommandBuilder creates a new mock instance.
func NewMockCommandBuilder(ctrl *gomock.Controller) *MockCommandBuilder {
	mock := &MockCommandBuilder{ctrl: ctrl}
	mock.recorder = &MockCommandBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandBuilder) EXPECT() *MockCommandBuilderMockRecorder {
	return m.recorder
}

// AddFilter mocks base method.
func (m *MockCommandBuilder) AddFilter(arg0 FilterFn) CommandBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFilter", arg0)
	ret0, _ := ret[0].(CommandBuilder)
	return ret0
}

// AddFilter indicates an expected call of AddFilter.
func (mr *MockCommandBuilderMockRecorder) AddFilter(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFilter", reflect.TypeOf((*MockCommandBuilder)(nil).AddFilter), arg0)
}

// AddInt mocks base method.
func (m *MockCommandBuilder) AddInt(arg0 string) CommandBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInt", arg0)
	ret0, _ := ret[0].(CommandBuilder)
	return ret0
}

// AddInt indicates an expected call of AddInt.
func (mr *MockCommandBuilderMockRecorder) AddInt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInt", reflect.TypeOf((*MockCommandBuilder)(nil).AddInt), arg0)
}

// AddResolver mocks base method.
func (m *MockCommandBuilder) AddResolver(arg0 CommandFn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddResolver", arg0)
}

// AddResolver indicates an expected call of AddResolver.
func (mr *MockCommandBuilderMockRecorder) AddResolver(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddResolver", reflect.TypeOf((*MockCommandBuilder)(nil).AddResolver), arg0)
}

// AddRest mocks base method.
func (m *MockCommandBuilder) AddRest(arg0 string) CommandBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRest", arg0)
	ret0, _ := ret[0].(CommandBuilder)
	return ret0
}

// AddRest indicates an expected call of AddRest.
func (mr *MockCommandBuilderMockRecorder) AddRest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRest", reflect.TypeOf((*MockCommandBuilder)(nil).AddRest), arg0)
}

// AddString mocks base method.
func (m *MockCommandBuilder) AddString(arg0 string) CommandBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddString", arg0)
	ret0, _ := ret[0].(CommandBuilder)
	return ret0
}

// AddString indicates an expected call of AddString.
func (mr *MockCommandBuilderMockRecorder) AddString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddString", reflect.TypeOf((*MockCommandBuilder)(nil).AddString), arg0)
}

// execute mocks base method.
func (m *MockCommandBuilder) execute(arg0 context.Context, arg1 discord.Session, arg2 Parser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "execute", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// execute indicates an expected call of execute.
func (mr *MockCommandBuilderMockRecorder) execute(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "execute", reflect.TypeOf((*MockCommandBuilder)(nil).execute), arg0, arg1, arg2)
}
