// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jonathanarnault/cgear-go/go/bot/discord (interfaces: Bot)

// Package discordmock is a generated GoMock package.
package discordmock

import (
	reflect "reflect"

	discordgo "github.com/bwmarrin/discordgo"
	gomock "github.com/golang/mock/gomock"
	discord "github.com/jonathanarnault/cgear-go/go/bot/discord"
)

// MockBot is a mock of Bot interface.
type MockBot struct {
	ctrl     *gomock.Controller
	recorder *MockBotMockRecorder
}

// MockBotMockRecorder is the mock recorder for MockBot.
type MockBotMockRecorder struct {
	mock *MockBot
}

// NewMockBot creates a new mock instance.
func NewMockBot(ctrl *gomock.Controller) *MockBot {
	mock := &MockBot{ctrl: ctrl}
	mock.recorder = &MockBotMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBot) EXPECT() *MockBotMockRecorder {
	return m.recorder
}

// AddCommandListener mocks base method.
func (m *MockBot) AddCommandListener(arg0 discord.CommandListener) func() {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCommandListener", arg0)
	ret0, _ := ret[0].(func())
	return ret0
}

// AddCommandListener indicates an expected call of AddCommandListener.
func (mr *MockBotMockRecorder) AddCommandListener(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCommandListener", reflect.TypeOf((*MockBot)(nil).AddCommandListener), arg0)
}

// ChannelCreateWithPermissions mocks base method.
func (m *MockBot) ChannelCreateWithPermissions(arg0, arg1, arg2 string, arg3 []*discordgo.PermissionOverwrite) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChannelCreateWithPermissions", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChannelCreateWithPermissions indicates an expected call of ChannelCreateWithPermissions.
func (mr *MockBotMockRecorder) ChannelCreateWithPermissions(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChannelCreateWithPermissions", reflect.TypeOf((*MockBot)(nil).ChannelCreateWithPermissions), arg0, arg1, arg2, arg3)
}

// Close mocks base method.
func (m *MockBot) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockBotMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBot)(nil).Close))
}

// MessageCreate mocks base method.
func (m *MockBot) MessageCreate(arg0, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageCreate", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MessageCreate indicates an expected call of MessageCreate.
func (mr *MockBotMockRecorder) MessageCreate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageCreate", reflect.TypeOf((*MockBot)(nil).MessageCreate), arg0, arg1)
}

// MessageDelete mocks base method.
func (m *MockBot) MessageDelete(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MessageDelete indicates an expected call of MessageDelete.
func (mr *MockBotMockRecorder) MessageDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageDelete", reflect.TypeOf((*MockBot)(nil).MessageDelete), arg0, arg1)
}
